#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace TicketApp
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class OrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public OrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TicketApp.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TicketApp.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<TicketApp.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TicketApp.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TicketApp.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<TicketApp.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TicketApp.Incident"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TicketApp.Incident> IncidentSet
		{
			get
			{
				return this.CreateQuery<TicketApp.Incident>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TicketApp.Queue"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TicketApp.Queue> QueueSet
		{
			get
			{
				return this.CreateQuery<TicketApp.Queue>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TicketApp.QueueItem"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TicketApp.QueueItem> QueueItemSet
		{
			get
			{
				return this.CreateQuery<TicketApp.QueueItem>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="TicketApp.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<TicketApp.SystemUser> SystemUserSet
		{
			get
			{
				return this.CreateQuery<TicketApp.SystemUser>();
			}
		}
	}
}
#pragma warning restore CS1591
