#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ticket_Web_App.Attributes;

namespace TicketApp
{
	
	
	/// <summary>
	/// Indicates the approval options for server-side synchronization or Email Router access.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum queue_emailrouteraccessapproval
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Empty = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approved = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PendingApproval = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rejected = 3,
	}
	
	/// <summary>
	/// Incoming email delivery method for the queue.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum queue_incomingemaildeliverymethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServerSideSynchronizationorEmailRouter = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ForwardMailbox = 3,
	}
	
	/// <summary>
	/// Incoming email filtering method.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum queue_incomingemailfilteringmethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allemailmessages = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailmessagesinresponsetoDynamics365email = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailmessagesfromDynamics365LeadsContactsandAccounts = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailmessagesfromDynamics365recordsthatareemailenabled = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Noemailmessages = 4,
	}
	
	/// <summary>
	/// Outgoing email delivery method for the queue.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum queue_outgoingemaildeliverymethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServerSideSynchronizationorEmailRouter = 2,
	}
	
	/// <summary>
	/// Type of queue that is automatically assigned when a user or queue is created. The type can be public, private, or work in process.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum queue_queuetypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Select whether the queue is public or private. A public queue can be viewed by all.A private queue can be viewed only by the members added to the queue.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum queue_queueviewtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Public = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Private = 1,
	}
	
	/// <summary>
	/// Status of the queue.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum queue_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the queue.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum queue_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
	}
	
	/// <summary>
	/// A list of records that require action, such as accounts, activities, and cases.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("queue")]
	[AppColumns("queueid", "ownerid")]
	public partial class Queue : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public Queue() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "queue";
		
		public const string EntityLogicalCollectionName = "queues";
		
		public const string EntitySetName = "queues";
		
		/// <summary>
		/// This attribute is no longer used. The data is now in the Mailbox.AllowEmailConnectorToUseCredentials attribute.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("allowemailcredentials")]
		[System.ObsoleteAttribute()]
		public System.Nullable<bool> AllowEmailCredentials
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("allowemailcredentials");
			}
		}
		
		/// <summary>
		/// Unique identifier of the business unit with which the queue is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessunitid")]
		[System.ObsoleteAttribute()]
		public Microsoft.Xrm.Sdk.EntityReference BusinessUnitId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("businessunitid");
			}
			set
			{
				this.SetAttributeValue("businessunitid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the queue record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the queue was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Select the mailbox associated with this queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultmailbox")]
		public Microsoft.Xrm.Sdk.EntityReference DefaultMailbox
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defaultmailbox");
			}
		}
		
		/// <summary>
		/// Description of the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.SetAttributeValue("description", value);
			}
		}
		
		/// <summary>
		/// Email address that is associated with the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailaddress")]
		public string EMailAddress
		{
			get
			{
				return this.GetAttributeValue<string>("emailaddress");
			}
			set
			{
				this.SetAttributeValue("emailaddress", value);
			}
		}
		
		/// <summary>
		/// This attribute is no longer used. The data is now in the Mailbox.Password attribute.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailpassword")]
		[System.ObsoleteAttribute()]
		public string EmailPassword
		{
			get
			{
				return this.GetAttributeValue<string>("emailpassword");
			}
		}
		
		/// <summary>
		/// Shows the status of the primary email address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailrouteraccessapproval")]
		public virtual queue_emailrouteraccessapproval? EmailRouterAccessApproval
		{
			get
			{
				return ((queue_emailrouteraccessapproval?)(EntityOptionSetEnum.GetEnum(this, "emailrouteraccessapproval")));
			}
			set
			{
				this.SetAttributeValue("emailrouteraccessapproval", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailsignature")]
		public Microsoft.Xrm.Sdk.EntityReference EmailSignature
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("emailsignature");
			}
			set
			{
				this.SetAttributeValue("emailsignature", value);
			}
		}
		
		/// <summary>
		/// This attribute is no longer used. The data is now in the Mailbox.UserName attribute.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailusername")]
		[System.ObsoleteAttribute()]
		public string EmailUsername
		{
			get
			{
				return this.GetAttributeValue<string>("emailusername");
			}
		}
		
		/// <summary>
		/// The default image for the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage")]
		public byte[] EntityImage
		{
			get
			{
				return this.GetAttributeValue<byte[]>("entityimage");
			}
			set
			{
				this.SetAttributeValue("entityimage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_timestamp")]
		public System.Nullable<long> EntityImage_Timestamp
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_url")]
		public string EntityImage_URL
		{
			get
			{
				return this.GetAttributeValue<string>("entityimage_url");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimageid")]
		public System.Nullable<System.Guid> EntityImageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the queue with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Information that specifies whether a queue is to ignore unsolicited email (deprecated).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ignoreunsolicitedemail")]
		public System.Nullable<bool> IgnoreUnsolicitedEmail
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ignoreunsolicitedemail");
			}
			set
			{
				this.SetAttributeValue("ignoreunsolicitedemail", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the data import or data migration that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Incoming email delivery method for the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incomingemaildeliverymethod")]
		public virtual queue_incomingemaildeliverymethod? IncomingEmailDeliveryMethod
		{
			get
			{
				return ((queue_incomingemaildeliverymethod?)(EntityOptionSetEnum.GetEnum(this, "incomingemaildeliverymethod")));
			}
			set
			{
				this.SetAttributeValue("incomingemaildeliverymethod", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Convert Incoming Email To Activities
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incomingemailfilteringmethod")]
		public virtual queue_incomingemailfilteringmethod? IncomingEmailFilteringMethod
		{
			get
			{
				return ((queue_incomingemailfilteringmethod?)(EntityOptionSetEnum.GetEnum(this, "incomingemailfilteringmethod")));
			}
			set
			{
				this.SetAttributeValue("incomingemailfilteringmethod", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Shows the status of approval of the email address by O365 Admin.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isemailaddressapprovedbyo365admin")]
		public System.Nullable<bool> IsEmailAddressApprovedByO365Admin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isemailaddressapprovedbyo365admin");
			}
		}
		
		/// <summary>
		/// Indication of whether a queue is the fax delivery queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isfaxqueue")]
		[System.ObsoleteAttribute()]
		public System.Nullable<bool> IsFaxQueue
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isfaxqueue");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who last modified the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the queue was last modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who last modified the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Link assignment input contract with queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_assignmentinputcontractid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_assignmentinputcontractid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_assignmentinputcontractid");
			}
			set
			{
				this.SetAttributeValue("msdyn_assignmentinputcontractid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_assignmentstrategy")]
		public virtual msdyn_queueassignmentstrategy? msdyn_assignmentstrategy
		{
			get
			{
				return ((msdyn_queueassignmentstrategy?)(EntityOptionSetEnum.GetEnum(this, "msdyn_assignmentstrategy")));
			}
			set
			{
				this.SetAttributeValue("msdyn_assignmentstrategy", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Define overflow rules for work items after it enters queue
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_inqueueoverflowrulesetid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_inqueueoverflowrulesetid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_inqueueoverflowrulesetid");
			}
			set
			{
				this.SetAttributeValue("msdyn_inqueueoverflowrulesetid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_intentfamilyid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_intentfamilyid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_intentfamilyid");
			}
			set
			{
				this.SetAttributeValue("msdyn_intentfamilyid", value);
			}
		}
		
		/// <summary>
		/// Shows whether the queue is set as default or not.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_isdefaultqueue")]
		public System.Nullable<bool> msdyn_isdefaultqueue
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_isdefaultqueue");
			}
			set
			{
				this.SetAttributeValue("msdyn_isdefaultqueue", value);
			}
		}
		
		/// <summary>
		/// Shows whether the queue is used as Omnichannel queue for work distribution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_isomnichannelqueue")]
		public System.Nullable<bool> msdyn_isomnichannelqueue
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_isomnichannelqueue");
			}
			set
			{
				this.SetAttributeValue("msdyn_isomnichannelqueue", value);
			}
		}
		
		/// <summary>
		/// Maximum queue size
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_maxqueuesize")]
		public System.Nullable<int> msdyn_maxqueuesize
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyn_maxqueuesize");
			}
			set
			{
				this.SetAttributeValue("msdyn_maxqueuesize", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for Operating hour associated with Queue
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_operatinghourid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_operatinghourid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_operatinghourid");
			}
			set
			{
				this.SetAttributeValue("msdyn_operatinghourid", value);
			}
		}
		
		/// <summary>
		/// Setting to enable/disable periodic processing of a queue
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_operatinghoursbasedassignment")]
		public System.Nullable<bool> msdyn_operatinghoursbasedassignment
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_operatinghoursbasedassignment");
			}
			set
			{
				this.SetAttributeValue("msdyn_operatinghoursbasedassignment", value);
			}
		}
		
		/// <summary>
		/// Define overflow rules for work items before it enters queue
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_prequeueoverflowrulesetid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_prequeueoverflowrulesetid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_prequeueoverflowrulesetid");
			}
			set
			{
				this.SetAttributeValue("msdyn_prequeueoverflowrulesetid", value);
			}
		}
		
		/// <summary>
		/// Priority of the queue to indicate conversation assignment order to the agent.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_priority")]
		public System.Nullable<int> msdyn_priority
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyn_priority");
			}
			set
			{
				this.SetAttributeValue("msdyn_priority", value);
			}
		}
		
		/// <summary>
		/// Setting to enable/disable periodic processing of a queue
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_processqueueperiodically")]
		public System.Nullable<bool> msdyn_processqueueperiodically
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_processqueueperiodically");
			}
			set
			{
				this.SetAttributeValue("msdyn_processqueueperiodically", value);
			}
		}
		
		/// <summary>
		/// Defines the type of channels handled by this queue
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_queuetype")]
		public virtual msdyn_queuetype? msdyn_queuetype
		{
			get
			{
				return ((msdyn_queuetype?)(EntityOptionSetEnum.GetEnum(this, "msdyn_queuetype")));
			}
			set
			{
				this.SetAttributeValue("msdyn_queuetype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique Name for the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_uniquename")]
		public string msdyn_uniquename
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_uniquename");
			}
			set
			{
				this.SetAttributeValue("msdyn_uniquename", value);
			}
		}
		
		/// <summary>
		/// Name of the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.SetAttributeValue("name", value);
			}
		}
		
		/// <summary>
		/// Number of Queue items associated with the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("numberofitems")]
		public System.Nullable<int> NumberOfItems
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("numberofitems");
			}
		}
		
		/// <summary>
		/// Number of Members associated with the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("numberofmembers")]
		public System.Nullable<int> NumberOfMembers
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("numberofmembers");
			}
		}
		
		/// <summary>
		/// Unique identifier of the organization associated with the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Outgoing email delivery method for the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("outgoingemaildeliverymethod")]
		public virtual queue_outgoingemaildeliverymethod? OutgoingEmailDeliveryMethod
		{
			get
			{
				return ((queue_outgoingemaildeliverymethod?)(EntityOptionSetEnum.GetEnum(this, "outgoingemaildeliverymethod")));
			}
			set
			{
				this.SetAttributeValue("outgoingemaildeliverymethod", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user or team who owns the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the business unit that owns the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier of the team who owns the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who owns the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Unique identifier of the owner of the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primaryuserid")]
		[System.ObsoleteAttribute()]
		public Microsoft.Xrm.Sdk.EntityReference PrimaryUserId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("primaryuserid");
			}
			set
			{
				this.SetAttributeValue("primaryuserid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queueid")]
		public System.Nullable<System.Guid> QueueId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("queueid");
			}
			set
			{
				this.SetAttributeValue("queueid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queueid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.QueueId = value;
			}
		}
		
		/// <summary>
		/// Type of queue that is automatically assigned when a user or queue is created. The type can be public, private, or work in process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queuetypecode")]
		public virtual queue_queuetypecode? QueueTypeCode
		{
			get
			{
				return ((queue_queuetypecode?)(EntityOptionSetEnum.GetEnum(this, "queuetypecode")));
			}
		}
		
		/// <summary>
		/// Select whether the queue is public or private. A public queue can be viewed by all. A private queue can be viewed only by the members added to the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queueviewtype")]
		public virtual queue_queueviewtype? QueueViewType
		{
			get
			{
				return ((queue_queueviewtype?)(EntityOptionSetEnum.GetEnum(this, "queueviewtype")));
			}
			set
			{
				this.SetAttributeValue("queueviewtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Status of the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual queue_statecode? StateCode
		{
			get
			{
				return ((queue_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual queue_statuscode? StatusCode
		{
			get
			{
				return ((queue_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		/// <summary>
		/// Version number of the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N queue_entries
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("queue_entries")]
		public System.Collections.Generic.IEnumerable<TicketApp.QueueItem> queue_entries
		{
			get
			{
				return this.GetRelatedEntities<TicketApp.QueueItem>("queue_entries", null);
			}
			set
			{
				this.SetRelatedEntities<TicketApp.QueueItem>("queue_entries", null, value);
			}
		}
		
		/// <summary>
		/// 1:N queue_system_user
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("queue_system_user")]
		public System.Collections.Generic.IEnumerable<TicketApp.SystemUser> queue_system_user
		{
			get
			{
				return this.GetRelatedEntities<TicketApp.SystemUser>("queue_system_user", null);
			}
			set
			{
				this.SetRelatedEntities<TicketApp.SystemUser>("queue_system_user", null, value);
			}
		}
		
		/// <summary>
		/// N:N queuemembership_association
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("queuemembership_association")]
		public System.Collections.Generic.IEnumerable<TicketApp.SystemUser> queuemembership_association
		{
			get
			{
				return this.GetRelatedEntities<TicketApp.SystemUser>("queuemembership_association", null);
			}
			set
			{
				this.SetRelatedEntities<TicketApp.SystemUser>("queuemembership_association", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_queue_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_queue_createdonbehalfby")]
		public TicketApp.SystemUser lk_queue_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<TicketApp.SystemUser>("lk_queue_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_queue_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_queue_modifiedonbehalfby")]
		public TicketApp.SystemUser lk_queue_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<TicketApp.SystemUser>("lk_queue_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_queuebase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_queuebase_createdby")]
		public TicketApp.SystemUser lk_queuebase_createdby
		{
			get
			{
				return this.GetRelatedEntity<TicketApp.SystemUser>("lk_queuebase_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_queuebase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_queuebase_modifiedby")]
		public TicketApp.SystemUser lk_queuebase_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<TicketApp.SystemUser>("lk_queuebase_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 queue_primary_user
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primaryuserid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("queue_primary_user")]
		public TicketApp.SystemUser queue_primary_user
		{
			get
			{
				return this.GetRelatedEntity<TicketApp.SystemUser>("queue_primary_user", null);
			}
			set
			{
				this.SetRelatedEntity<TicketApp.SystemUser>("queue_primary_user", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
