#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ticket_Web_App.Attributes;

namespace TicketApp
{
	
	
	/// <summary>
	/// Identifies the type of queue item, such as the specific activity type, case, or article.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum queueitem_objecttypecode
	{
		
		/// <summary>
		/// Task performed, or to be performed, by a user for planning or running a campaign.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CampaignActivity = 4402,
		
		/// <summary>
		/// Organizational Knowledge Article Template for Internal and external creation of Knowledge Articles.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleTemplate = 10244,
		
		/// <summary>
		/// Specify the maintenance booking dates for the agreement.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementBookingDate = 11201,
		
		/// <summary>
		/// Holds information about the redemption of an invite.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InviteRedemption = 10371,
		
		/// <summary>
		/// Overflow action configurations.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OverflowActionConfig = 10751,
		
		/// <summary>
		/// Activity to track a telephone call.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
		
		/// <summary>
		/// Specify the maintenance bookings for the agreement.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementBookingSetup = 11206,
		
		/// <summary>
		/// Session for interacting with a customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Session = 10804,
		
		/// <summary>
		/// Response to a survey.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicesurveyresponse = 10694,
		
		/// <summary>
		/// Generic activity representing work needed to be done.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		/// <summary>
		/// Organizational knowledge for internal and external use.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticle = 9953,
		
		/// <summary>
		/// Store service tasks that are to be performed for this work order
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderServiceTask = 11270,
		
		/// <summary>
		/// Records inventory adjustments
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InventoryTransfer = 11232,
		
		/// <summary>
		/// Activity that tracks the delivery of a letter. The activity can contain the electronic copy of the letter.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Letter = 4207,
		
		/// <summary>
		/// Specify the invoices for this agreement.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementInvoiceSetup = 11209,
		
		/// <summary>
		/// Task performed, or to be performed, by a user. An activity is any action for which an entry can be made on a calendar.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Activity = 4200,
		
		/// <summary>
		/// Specify work order incidents reported to you by the client. These are also referred to as problem codes.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderIncident = 11266,
		
		/// <summary>
		/// Specify individual time windows under a time group.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimeGroupDetail = 11175,
		
		/// <summary>
		/// Outbound activity entity
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Outboundmessage = 11358,
		
		/// <summary>
		/// Work orders store all information about the job performed for an account. Stores incident details, resource, expenses, tasks, communications, billing and more
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrder = 11263,
		
		/// <summary>
		/// Records inventory adjustments
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InventoryAdjustment = 11229,
		
		/// <summary>
		/// Activity that tracks a survey invitation sent to a person.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicesurveyinvite = 10692,
		
		/// <summary>
		/// Commitment representing a time interval with start/end times and duration.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		/// <summary>
		/// System operation used to perform lengthy and asynchronous operations on large data sets, such as distributing a campaign activity or quick campaign.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuickCampaign = 4406,
		
		/// <summary>
		/// Response from an existing or a potential new customer for a campaign.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CampaignResponse = 4401,
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialActivity = 4216,
		
		/// <summary>
		/// Activity that is delivered using email protocols.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		/// <summary>
		/// Alerts that notify schedule board users of booking issues or information.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookingAlert = 11151,
		
		/// <summary>
		/// The Master appointment of a recurring appointment series.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringAppointment = 4251,
		
		/// <summary>
		/// An activity which is used to share information between the user and the customer on the portal.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortalComment = 10372,
		
		/// <summary>
		/// Specify time groups consisting of multiple time windows to be used for scheduling, for example.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FulfillmentPreference = 11174,
		
		/// <summary>
		/// Activity offered by the organization to satisfy its customer's needs. Each service activity includes date, time, duration, and required resources.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceActivity = 4214,
		
		/// <summary>
		/// Specify the invoice dates for the agreement.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementInvoiceDate = 11207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicealert = 10682,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CopilotTranscript = 11013,
		
		/// <summary>
		/// Activity that tracks call outcome and number of pages for a fax and optionally stores an electronic copy of the document.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4204,
		
		/// <summary>
		/// For internal use only. Entity which stores association data of Dynamics 365 records with Microsoft Teams chat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Teamschat = 10228,
		
		/// <summary>
		/// Record all services proposed and performed for work order
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderService = 11269,
		
		/// <summary>
		/// Tracks the interaction between the agents and customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conversation = 10787,
		
		/// <summary>
		/// Tracks the interactions between the agents and customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ongoingconversation_Deprecated = 10775,
		
		/// <summary>
		/// Service request case associated with a contract.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Case = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTAlert = 10471,
	}
	
	/// <summary>
	/// Status of the queue item.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum queueitem_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the queue item.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum queueitem_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
	}
	
	/// <summary>
	/// A specific item in a queue, such as a case record or an activity record.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("queueitem")]
	[AppColumns("queueitemid", "objectid", "queueid")]
	public partial class QueueItem : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public QueueItem() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "queueitem";
		
		public const string EntityLogicalCollectionName = "queueitems";
		
		public const string EntitySetName = "queueitems";
		
		/// <summary>
		/// Shows who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Shows who created the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Shows the date the record was assigned to the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("enteredon")]
		public System.Nullable<System.DateTime> EnteredOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("enteredon");
			}
		}
		
		/// <summary>
		/// Shows the conversion rate of the record's currency. The exchange rate is used to convert all money fields in the record from the local currency to the system's default currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Unique identifier of the data import or data migration that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Shows who last updated the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was last updated. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who last modified the queueitem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Liveworkstream this queue item belongs to
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_liveworkstreamid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_liveworkstreamid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_liveworkstreamid");
			}
			set
			{
				this.SetAttributeValue("msdyn_liveworkstreamid", value);
			}
		}
		
		/// <summary>
		/// This attribute is used by Unified Routing system to decide whether to Skip Sync Call to Omnichannel Service or not.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_skipursync")]
		public System.Nullable<bool> msdyn_skipursync
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_skipursync");
			}
			set
			{
				this.SetAttributeValue("msdyn_skipursync", value);
			}
		}
		
		/// <summary>
		/// Choose the activity, case, or article assigned to the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		public Microsoft.Xrm.Sdk.EntityReference ObjectId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("objectid");
			}
			set
			{
				this.SetAttributeValue("objectid", value);
			}
		}
		
		/// <summary>
		/// Select the type of the queue item, such as activity, case, or appointment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objecttypecode")]
		public virtual queueitem_objecttypecode? ObjectTypeCode
		{
			get
			{
				return ((queueitem_objecttypecode?)(EntityOptionSetEnum.GetEnum(this, "objecttypecode")));
			}
		}
		
		/// <summary>
		/// Unique identifier of the organization with which the queue item is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user or team who owns the queue item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
		}
		
		/// <summary>
		/// Unique identifier of the business unit that owns the queue item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who owns the queue item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Priority of the queue item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("priority")]
		[System.ObsoleteAttribute()]
		public System.Nullable<int> Priority
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("priority");
			}
			set
			{
				this.SetAttributeValue("priority", value);
			}
		}
		
		/// <summary>
		/// Choose the queue that the item is assigned to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queueid")]
		public Microsoft.Xrm.Sdk.EntityReference QueueId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("queueid");
			}
			set
			{
				this.SetAttributeValue("queueid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the queue item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queueitemid")]
		public System.Nullable<System.Guid> QueueItemId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("queueitemid");
			}
			set
			{
				this.SetAttributeValue("queueitemid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queueitemid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.QueueItemId = value;
			}
		}
		
		/// <summary>
		/// Sender who created the queue item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sender")]
		[System.ObsoleteAttribute()]
		public string Sender
		{
			get
			{
				return this.GetAttributeValue<string>("sender");
			}
			set
			{
				this.SetAttributeValue("sender", value);
			}
		}
		
		/// <summary>
		/// Status of the queue item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("state")]
		[System.ObsoleteAttribute()]
		public System.Nullable<int> State
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("state");
			}
			set
			{
				this.SetAttributeValue("state", value);
			}
		}
		
		/// <summary>
		/// Shows whether the queue record is active or inactive. Inactive queue records are read-only and can't be edited unless they are reactivated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual queueitem_statecode? StateCode
		{
			get
			{
				return ((queueitem_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the queue item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("status")]
		[System.ObsoleteAttribute()]
		public System.Nullable<int> Status
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("status");
			}
			set
			{
				this.SetAttributeValue("status", value);
			}
		}
		
		/// <summary>
		/// Select the item's status.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual queueitem_statuscode? StatusCode
		{
			get
			{
				return ((queueitem_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Shows the title or name that describes the queue record. This value is copied from the record that was assigned to the queue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("title")]
		public string Title
		{
			get
			{
				return this.GetAttributeValue<string>("title");
			}
			set
			{
				this.SetAttributeValue("title", value);
			}
		}
		
		/// <summary>
		/// Recipients listed on the To line of the message for email queue items.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("torecipients")]
		[System.ObsoleteAttribute()]
		public string ToRecipients
		{
			get
			{
				return this.GetAttributeValue<string>("torecipients");
			}
			set
			{
				this.SetAttributeValue("torecipients", value);
			}
		}
		
		/// <summary>
		/// Choose the local currency for the record to make sure budgets are reported in the correct currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version number of the queue item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Shows who is working on the queue item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workerid")]
		public Microsoft.Xrm.Sdk.EntityReference WorkerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("workerid");
			}
			set
			{
				this.SetAttributeValue("workerid", value);
			}
		}
		
		/// <summary>
		/// Shows the date and time when the queue item was last assigned to a user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workeridmodifiedon")]
		public System.Nullable<System.DateTime> WorkerIdModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("workeridmodifiedon");
			}
		}
		
		/// <summary>
		/// N:1 Incident_QueueItem
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Incident_QueueItem")]
		public TicketApp.Incident Incident_QueueItem
		{
			get
			{
				return this.GetRelatedEntity<TicketApp.Incident>("Incident_QueueItem", null);
			}
			set
			{
				this.SetRelatedEntity<TicketApp.Incident>("Incident_QueueItem", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_queueitem_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_queueitem_createdonbehalfby")]
		public TicketApp.SystemUser lk_queueitem_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<TicketApp.SystemUser>("lk_queueitem_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_queueitem_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_queueitem_modifiedonbehalfby")]
		public TicketApp.SystemUser lk_queueitem_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<TicketApp.SystemUser>("lk_queueitem_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_queueitembase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_queueitembase_createdby")]
		public TicketApp.SystemUser lk_queueitembase_createdby
		{
			get
			{
				return this.GetRelatedEntity<TicketApp.SystemUser>("lk_queueitembase_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_queueitembase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_queueitembase_modifiedby")]
		public TicketApp.SystemUser lk_queueitembase_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<TicketApp.SystemUser>("lk_queueitembase_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_queueitembase_workerid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_queueitembase_workerid")]
		public TicketApp.SystemUser lk_queueitembase_workerid
		{
			get
			{
				return this.GetRelatedEntity<TicketApp.SystemUser>("lk_queueitembase_workerid", null);
			}
			set
			{
				this.SetRelatedEntity<TicketApp.SystemUser>("lk_queueitembase_workerid", null, value);
			}
		}
		
		/// <summary>
		/// N:1 queue_entries
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("queueid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("queue_entries")]
		public TicketApp.Queue queue_entries
		{
			get
			{
				return this.GetRelatedEntity<TicketApp.Queue>("queue_entries", null);
			}
			set
			{
				this.SetRelatedEntity<TicketApp.Queue>("queue_entries", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
